# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='for_form',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
