# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160401_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='nform',
            name='description',
            field=models.TextField(default='Enter webform description here'),
        ),
    ]
